name: 'Run Private GitHub Action'
description: 'Runs a privately-hosted GitHub Action'
inputs:
  action_repository:
    description: The repository of the private action to run
    required: true

  action_ref:
    description: The ref to check out for the private action repository
    required: false
    default: ''

  action_token:
    description: The GitHub token to use for checking out the private repository
    required: true
  

outputs: 
  action_outputs:
    value: toJSON(steps.run_private_action.outputs)

runs:
  using: 'composite'
  steps:
    # Create a directory for checking out the private action repository
    - name: Create Checkout Directory
      id: create_checkout_directory
      shell: bash
      run: mkdir -p ./.github/actions/run-private-action/

    # Checkout the private action
    - name: Checkout Private Action
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.action_repository }}
        ref: ${{ inputs.action_ref }}
        token: ${{ inputs.action_token }}
        path: ./.github/actions/run-private-action/

    # Remove any inputs that shouldn't be passed to the private action
    - name: Remove Wrapper Inputs
      id: clean_inputs
      shell: bash
      working-directory: ./.github/actions/run-private-action/
      # If JQ is not installed, install it (using )
      run: |
        if ! command -v jq &> /dev/null; then
          if command -v apt &> /dev/null; then
            sudo apt install -y jq
          elif command -v yum &> /dev/null; then
            sudo yum install -y jq
          else
            echo "Unable to install jq"
            exit 1
          fi
        fi
        INPUTS_JSON=$(cat <<EOFPRIVATEACTIONJSON
        ${{ toJSON(inputs) }}
        EOFPRIVATEACTIONJSON
        )
        echo "Inputs JSON: $INPUTS_JSON"
        echo "$INPUTS_JSON" >> .inputs.json
        CLEANED_INPUTS="$(jq 'del(.action_repository)' .inputs.json | jq 'del(.action_ref)' | jq 'del(.action_token)')"
        CLEANED_INPUTS="$(jq 'del(.action_repository)' .inputs.json | jq 'del(.action_ref)' | jq 'del(.action_token)')"
        echo "Cleaned Inputs JSON: $CLEANED_INPUTS"
        echo ::set-output name=cleaned_inputs::"$CLEANED_INPUTS"

    # Create a directory for checking out the private action repository
    - name: Output inputs
      shell: bash
      run: echo "${{ steps.clean_inputs.outputs.cleaned_inputs }}"

    # Run the private action
    - name: Run Private Action
      id: run_private_action
      uses: ./.github/actions/run-private-action/
      with: ${{ fromJSON( steps.clean_inputs.outputs.cleaned_inputs ) }}
