name: 'Run Private GitHub Action'
description: 'Runs a privately-hosted GitHub Action'
inputs:
  repository:
    description: The repository of the private action to run
    required: true

  ref:
    description: The ref to check out for the private action repository
    required: false
    default: ''

  token:
    description: The GitHub token to use for checking out the private repository
    required: true
  
  inputs:
    description: Inputs for the private action
    required: false
    default: fromJSON('{}')

outputs: ${{ steps.run_private_action.outputs }}

runs:
  using: 'composite'
  steps:
    # Generate a unique checkout path for the action
    - name: Generate Unique Checkout Path
      id: generate_checkout_path
      shell: bash
      run: echo ::set-output name=checkout_path::"${{ github.workspace }}/.github/actions/private-action-${RANDOM}${RANDOM}${RANDOM}"

    # Checkout the private action
    - name: Checkout Private Action
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}
        path: ${{ steps.generate_checkout_path.outputs.checkout_path }}

    # Run the private action
    - name: Run Private Action
      id: run_private_action
      uses: ${{ steps.generate_checkout_path.outputs.checkout_path }}
      with: ${{ inputs.inputs }}
